---
:authentication:
  :method: OAuth2
  :oauth2_client_id: 329313322179-mb72h2eckffrvv8i2780099r09fijr0v.apps.googleusercontent.com
  :oauth2_client_secret: jFey0to-FxP5L5rgsrmiKP_p
  :developer_token: k65d1wRxWpRpQRpYMwU-pw
  :client_customer_id: 266-136-8280
  :user_agent: csp
  :oauth2_token:
    :access_token: ya29.Glt-BcUaZ9mel475Cx391nI0RHC7cfv2hVsOt51BTNJfv7Cl0VX2Ua4H11TxCg_N6QR8--9xZoaFWaOsa24LVGnu9niCA-IBE6Av1n4S09YfKH9Cd_vwgAAznjyR
    :refresh_token: 1/C5jEgl37c_OnLE2ksrYSmttumoMe35vtLlXMBY6VpJA
    :issued_at: 2018-03-14 15:23:13.335192000 -07:00
    :expires_in: 3600
    :id_token:
:service:
  :environment: PRODUCTION
:connection:
  :enable_gzip: false
:library:
  :log_level: INFO
