
HOST_NAME: < your_development_host >

SECRET_KEY_BASE: ***

SENDGRID_USERNAME: ***
SENDGRID_PASSWORD: ***

DEVISE_SECRET_KEY: ***

LINKEDIN_KEY: ***
LINKEDIN_SECRET: ***

AWS_ACCESS_KEY_ID: ***
AWS_SECRET_ACCESS_KEY: *
S3_BUCKET: ***

test:
  SECRET_KEY_BASE: ***

production:
  HOST_NAME: ***
  S3_BUCKET: ***